application: gdea-home
version: v1
runtime: python27
api_version: 1
threadsafe: no

handlers:


- url: /
  script: main.app
  secure: always
  
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  secure: always
  
- url: /backg\.jpg
  static_files: static/backg.jpg
  upload: static/backg\.jpg
  secure: always
  
- url: /icon\.png
  static_files: static/icon.png
  upload: static/icon\.png
  secure: always

- url: /static/base(\.[0-9])\.css
  static_files: static/base.css
  upload: static/base\.css
  secure: always
  
- url: /assets/base(\.[0-9])\.css
  static_files: assets/base.css
  upload: assets/base\.css
  secure: always

- url: /static
  static_dir: static
  secure: always
  
- url: /assets
  static_dir: assets
  secure: always

- url: /.*
  script: main.app
  secure: always
 
 
